language: python
dist: trusty
sudo: required
python:
- '2.7'
install:
- python setup.py install
script:
- true
before_install:
- sudo apt-get update
- sudo apt-get install nodejs
deploy:
    provider: pypi
    user: athanaseus
    on:
       tags: true
       distributions: sdist bdist_wheel
repo: ratt-ru/ragavi
