language: python
dist: trusty
sudo: required
python:
- '2.7'
install:
- python setup.py install
script:
- true
before_install:
- sudo apt-get update
- sudo apt-get install nodejs
- pip install --upgrade pip
deploy:
  provider: pypi
  user: mulan-94
  password:
    secure: OZRwMuTUyk0m8zyg6TfxnU6+6uu+SoeDc9bXkx2GY9rF/HSU3pD8XxWl/Ectb7MZWxFzlWaNr5S7/g+ZBwaeRsg4na80D0XmU1Qdu/eKaKW1Ji6J/JSf525u/p/XkIGR8IHD2BGuzRLxT7MBs3VpGfkJdrHOXN75mFrvIe7LSRCxpIzTWFHbT9zrqxXE8VEDJO5lZEyWyCsstGImT0wr/wQHXc5YhnjpSsVoSxXpryGot95J3Uv7rjO3CeziNZ14LndSFhmRQixxtY6P+IMDg1++NvyRQUHC5hMIynsNiQa+BUaCrN95MAmO7SY36eGvrrurJZ5LRZ2Zl90j92HW+M0hD1HPo8ba1SDvzCH4qrJgq/vlvUGH/UYN6awReegEk2fnXk9pFw3rNRQPXQnbFU3yhAC/TzDXl7ARE8A/MBDpgOG6A79r3B0dlvFzp0KuCYDG8bVkqJiLyEIiQpQhA/mxhuaiKWdhF5BpJjU8Z/4gQzecow2bNUuXNAD7zxup7PCLiyHRBDD+cUuDnSRUPK+AdJJIydsp/yoyIMHlDYsTqT/RSPP24eSnZytkgUGFyKJzUgiGruou6JUmkSjAUGPmjg1+Wlm53kGbHBHJXxcAvJ96SiQ6mox2LUDa8Zc4yRK4Ag11qZOJOZ5QUYlOqOU+cQYCizuEG4h0gsxhfQA=
  on:
    tags: true
    distributions: sdist bdist_wheel
repo: ratt-ru/ragavi
