language: python
dist: xenial
sudo: required
matrix:
  include:
    - env: PYTHON=py3
services: 
 - docker
install:
 - true
script:
 - docker build . -f .travis/${PYTHON}.docker
deploy:
  provider: pypi
  user: mulan-94
  password:
    secure: VmmMC4BaMCr/VxkH773/+wIW6zsa8mtd3qtaMhJFmB0BeIPO27wRmg6nd/kigzc0gPhOzWC8oyP5JXBvwfCGdhuimXZc8NZsvxVFPXkr60U1hAalPTlhufX9Rbuj+zat+mmuooocxFvs3mrhmHgP0v19V5OgItzmg7xFInDmVNrQGW0nnJe3Ug446n2j8mIDkKvvoyACtVrnoVKlaQsGtpVJ9uPE6NHq+sdnqwR8+YgzODjd0R/IsJDjFqzBYDOqFzwkYp4wVvvtaME/oToKYqH0BRMP4D2lg8stH4VFEQX99GmOVgDM4m2dlRG+WJ7KZRXZJwpR32z0TXFA0I1ET7+y1Q/+E3BGm7gwCmCEU+Er2vXO5sOGzTrI1gWPvP8goK3gcuKMZf0PAvX0TEJww4zDgagA9XlzKrXmQjQScX7TZZmkH9kRIWxPScaHqLHaPsNdK9neE4tc4xEt+OWNx8wT0jynmHWwsbKJrOrxw5viAzxLsTmLpwKvAhhLppotvy60U9ZMDDhkg37DFcSmZhaqPAjaYrs+mxMXgwwqjogPA1l4MwLXBx88hPTDIT954ANXww95FqFq/12bPQpZ6y0Oxze2X/4bT7oetKVP2qwJhjHWxiVWKBTulstzT9pfJS6vrSlMDCwVjXIcFF6huyXaDkHTDEtlKUMjXuey4/8=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: ratt-ru/ragavi
