language: python
sudo: false
python:
- '2.7'
install:
- python setup.py install
script:
- true
before_install:
- sudo apt-get install nodejs, casacore-dev
deploy:
    provider: pypi
    user: athanaseus
    on:
       tags: true
       distributions: sdist bdist_wheel
       repo: ratt-ru/ragavi
